# resolver: nightly-2016-10-31
resolver: nightly-2016-12-13
extra-package-dbs: []
extra-deps:
  - 'QuickCheck-2.9.2'

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'
